-- CreateEnum
CREATE TYPE "OnboardingStatus" AS ENUM ('ACCOUNT_CREATION', 'PERSONAL_INFO', 'INITIAL_BALANCE', 'MONTHLY_BUDGET', 'CATEGORIES_SETUP', 'NOTIFICATIONS', 'COMPLETE');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "onboardingStatus" "OnboardingStatus" DEFAULT 'ACCOUNT_CREATION';
